export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const UPDATE_SEL_MONTH = 'UPDATE_SEL_MONTH'
export const UPDATE_SEL_WEEK = 'UPDATE_SEL_WEEK'
export const UPDATE_SEL_DAY = 'UPDATE_SEL_DAY'

export const UPDATE_IS_LOGIN = 'UPDATE_IS_LOGIN'

export const UPDATE_MONTH_SCHEDULE = 'UPDATE_MONTH_SCHEDULE'
export const UPDATE_WEEK_SCHEDULE = 'UPDATE_WEEK_SCHEDULE'
export const UPDATE_DAY_SCHEDULE = 'UPDATE_DAY_SCHEDULE'

export const INIT_DATA = 'INIT_DATA'

export const UPDATE_NETERRCOUNT = 'UPDATE_NETERRCOUNT'
